# stats available at
# https://travis-ci.org/strukturag/libde265/
language: cpp
compiler:
  - gcc
env:
  - HOST= 
  - HOST=cmake
  
matrix:
  include:
    - compiler: clang
      env: HOST=

before_install:
  - sudo add-apt-repository -y ppa:kalakris/cmake
  - sudo apt-get update -qq
  - sudo apt-get install cmake

before_script:
  - if [ "$HOST" = "cmake" ]; then cmake .; fi

script:
  - sh -c "if [ -z "$HOST" ] && [ -z "$DECODESTREAMS" ]; then ./scripts/check_licenses.sh; fi"
  - make
  - sh -c "if [ -z "$HOST" ] && [ -z "$DECODESTREAMS" ]; then make dist && mkdir dist-test && cd dist-test && tar xzf ../libde265-*.tar.gz && cd libde265-* && ./configure && make; fi"
  - sh -c "if [ -z "$HOST" ] && [ -z "$DECODESTREAMS" ]; then make dist && mkdir dist-cmake-test && cd dist-cmake-test && tar xzf ../libde265-*.tar.gz && cd libde265-* && cmake . && make; fi"
  
