
language: cpp
compiler:
  - gcc
git:
  depth: 3

# safelist
branches:
  only:
  - internal
  - travisCITest
  
before_install:
  # We need cmake
  - sudo add-apt-repository -y ppa:kalakris/cmake
  - sudo apt-get update -qq
  - sudo apt-get install cmake

before_script:
  - pwd
  - cmake .

script:
  - make
  
after_success:
  # Here we could deploy the binariies
  
deploy:
  # We need the compiled files
  skip_cleanup: true
  
  