# stats available at
# https://ci.appveyor.com/project/strukturag/libde265
version: #{build}

os:
  - Windows Server 2012 R2

environment:
  matrix:
    - GENERATOR: "Visual Studio 12 2013"

platform:
  - x64

configuration:
  - Release

build:
  verbosity: normal

install:
  - git clone https://github.com/strukturag/libde265-data.git

build_script:
  - ps: if($env:PLATFORM -eq "x64") { $env:CMAKE_GEN_SUFFIX=" Win64" }
  - cmake "-G%GENERATOR%%CMAKE_GEN_SUFFIX%" -H. -Bbuild
  - cmake --build build --config %CONFIGURATION%

artifacts:
  - path: build
