# stats available at
# https://ci.appveyor.com/project/strukturag/libde265
image: Visual Studio 2017

environment:
  matrix:
    - GENERATOR: "Visual Studio 15 2017"

platform:
  - x64

configuration:
  - Release

build:
  verbosity: normal

build_script:
  - ps: if($env:PLATFORM -eq "x64") { $env:CMAKE_GEN_SUFFIX=" Win64" }
  - cmake "-G%GENERATOR%%CMAKE_GEN_SUFFIX%" -H. -Bbuild
  - cmake --build build --config %CONFIGURATION%

artifacts:
  - path: build
